# Generated by Django 5.1.2 on 2025-07-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('pick_up_point', 'Пункт выдачи'), ('delivery', 'Курьерская доставка'), ('mail_rf', 'Почта России')], default='самовывоз из магазина', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('cash', 'Наличными'), ('card_online', 'Картой онлайн'), ('card_courier', 'Картой курьеру')], default='картой', max_length=50),
        ),
    ]
